# Generated by Django 2.0.3 on 2018-06-17 11:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challengeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('group', models.CharField(max_length=10)),
                ('pt', models.IntegerField()),
                ('times', models.IntegerField(default=0)),
                ('solvers', models.CharField(blank=True, default='', max_length=300, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('flag', models.CharField(max_length=128)),
            ],
        ),
    ]
