# Generated by Django 2.0.3 on 2018-06-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminEdit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeinfo',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
